{
 "title": "Monitoramento da rede",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Média Latência",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  latency\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Média Download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  download\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Média Upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  upload\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latência",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  latency\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  download\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dh_historico AS \"time\",\n  upload\nFROM tbl_historico_rede\nORDER BY 1"
    }
   ]
  },
  { "title": "Alertas", "type": "alertlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 } }
 ]
}