app:
  scheduler:
    coletarDadosRede: "0/45 * * * * *"
    removerHistorico: "0 0/50 * * * *"
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/db_rede
    username: tcb
    password: tcb
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: false
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
